# Lab-rapport

## Introduksjon

I dette laboratorieforsøket gjennomførte vi ekstraksjon og analyse av proteiner. Hensikten var å påvise to ulike proteiner, UBF fra cellekjernen og ribosomal s6 fra cytosol. Et protein er sammensatt av flere aminosyrer som til sammen danner flere kjeder, disse kjedene settes deretter sammen og danner sløyfer på kjeden av aminosyrer. Bindinger dannes mellom deler av kjeden som ligger langt fra hverandre og danner til slutt selve proteinet. Sammensetningen av aminosyrene i proteinet vil avgjøre hva slags oppgaver proteinet har. Proteiner kan fungere i nødvendige og kritiske oppgaver i kroppens struktur og funksjon, i tillegg til å være viktige i regulering av vev og organer. Proteiner kan for eksempel fungere som antistoffer for å beskytte kroppen mot virus og bakterier, være enzymer i fordøyelsen vår, fungere som transportproteiner som bringer signaler over cellemembraner [@alberts2015] eller være viktige for dannelsen av nye proteiner.

Proteiner som er viktige for å danne nye proteiner er blant annet UBF og S6. UBF er en transkripsjonsfaktor som finnes i cellekjernen. Denne spiller en viktig rolle i aktiveringen av transkripsjonen av ribosomalt RNA. UBF muliggjør binding av enzymet polymerase 1 for senere å kunne starte transkripsjon av ribosomalt RNA [@copenhaver1994]. S6 protein er et ribosomalt protein som er en del av underenheten 40S. Underenheten 40S er en del av ribosomet som finnes i Cytosol. S6 proteinet er involvert i translasjonen av nye proteiner [@puighermanal2017].

For å påvise proteiner både i cytosol og cellekjernen kreves ulike buffere med tanke på hvor i cellen de befinner seg. For å finne proteiner i cytosol brukes Hepes buffer, og Laemmle buffer for å finne proteiner i cellekjernen. Etter dette ble proteinene separert og analysert ved bruk av western blotting. Vi forventet å finne UBF innenfor 94-97 Kilodaton, og S6 på 32 Kda.

## Metode

Homogenisering For å detektere proteiner benyttes ofte en metode som kalles western blotting. Dette er en metode som går ut på å påvise proteiner gjennom binding og gjenkjennelse av antistoffer til ett eller flere proteiner vi er ute etter [@bass2017]. I forkant av western blotting må prøvene homogeniseres. Dette innebærer å skille ut de proteinene vi er interessert i. Prøvene vi skulle analysere var muskelfibre fra muskelbiopsi. Vi benyttet to ulike buffere, Hepes og Laemmle, for å å påvise ønskede proteiner. Først ble muskelfibre homogenisert med Hepes, og sentrifugert slik at supernatant og pellet ble dannet. Disse substansene ble skilt fra hverandre, og pellet ble deretter homogenisert med Laemmle og sentrifugert. Igjen dannet det seg supernatant og pellet, som ble separert fra hverandre. Proteinkonsentrasjonene i Hepes og Laemmle ble målt gjennom sammenligning med Bradford reagent (standardkurve).

Western blotting Når prøvene ble homogenisert og proteinkonsentrasjonen ble beregnet, så ble prøvene loadet i en gel (sds-page). Ladderen gikk i første brønn, og deretter prøvene. Hver prøve var todelt og bestod av en med hepes buffer og en annen med laemmle buffer. Deretter koblet vi på strøm i 40 minutter med 250 volt. Etter proteinene ble separert i gelen var neste fase en electro transfer, her skulle proteinene overføres fra gelen og over til en membran.

Blocking og antistoffer Membranen ble delt opp i flere deler og hver del ble blandet med et blokkeringsmiddel som bestod av tørrmelk, tween-20 og TBS buffer (Tris-Buffered Saline). Etter 60 minutter ble blokkeringmiddelet fjernet. To ulike primære antistoffer, rRNA s6 og UBF, ble deretter blandet med membranene. Prøvene stod i et kjøleskap på et vippebrett i et døgn, for å sørge for at antistoffene festet seg til proteinene skikkelig. Etter å ha stått i et døgn ble membranen vasket. Sekundære antistoffer ble deretter tilsatt membranene. De sekundære antistoffene gjenkjenner og binder seg til de primære antistoffene. Fordi de sekundære antistoffene gir fra seg lys, kunnen vi indirekte detektere proteinene vi var ute etter når vi tok bilde av membranene. Membranene ble vasket etter å ha stått i 1-2 timer med sekundære antistoffer. Deretter tok vi bilde av hver membran. Bildene ble analysert på en datamaskin, der bildene av membranene ble lagt over bildene av ladderen som var vår referanse. Med linjal sammenlignet vi molekylærvekten til hvert protein.

## Resultater

Resultatene viste at vi fant både UBF og s6 i forsøket. Vi fant både UBF og s6 i Laemmle bufferen. Selv om s6 ble påvist i større grad med Laemmle bufferen, kunne man til dels også se dette proteinet i Hepes bufferen.

## Diskusjon

Som forventet fant vi UBF i Laemmle løsningen. Fordi Laemmle er en sterk løsning, skal denne bufferen kunne finne proteiner i cellekjernen. Vi regnet med å finne s6 med Hepes siden dette proteinet finnes i cytosol. Hepes er en svakere buffer enn Leammle og skulle potensielt ha funnet proteinene som befinner seg i cytosol. Vi fant mest av s6 i Leammle. Dette kan skyldes at s6 også finnes i cellekjernen (pga. transport inn og ut av cellekjernen). En annen mulighet er at ikke alle proteiner som ikke befinner seg i cellekjernen ble skilt ut gjennom en gjennomføring av homogenisering med Hepes. Hadde vi gjennomført dette en gang til (homogenisering med Hepes), kan det hende vi hadde funnet mer s6 i Hepes løsningen, fordi vi muligens hadde sikret oss at alle proteiner som ikke finnes i cellekjernen hadde blitt skilt ut. En annen mulig feilkilde kan være at maskinen som tok bilde av membranen ikke klarte å tilpasse seg det sterke lyset fra prøvene som lå i Laemmle bufferen. Dette kan muligens forklare de svake båndene som viste s6 i Hepes prøvene på bildet som ble tatt.

Western blotting er en metode som innebærer mange ulike steg, og er en kompleks prosess. For at resultatene skal være reliable og valide kreves nøyaktighet. Man må blant annet være konsekvent når det kommer til valg av buffer for homogenisering og ekstraksjon av ønskede proteiner. Gelsammensetningen har noe å si for hvordan proteinene vandrer etter molekylærstørrelse, og både spenningen man tar i bruk og hvor lenge elektroforese og elektrotransfer skal foregå kan påvirke utfallet for proteintransporten. Dersom varigheten er for lang kan små proteiner "forsvinne" fordi de potensielt kan vandre ut av gelen og memebranen. I tillegg kan varigheten på blockingen påvirke bindingen av primære antistoffer til målproteinet. For eksempel kan for lite varighet på blockingen føre til at primære antistoffer binder seg til ikke-spesifikke steder på membranen, slik at målproteinet ikke blir påvist. Bildeprogrammet og type kamera for analyse av båndene kan også påvirke resultatene, og er noe man må ha i bakhodet når man fremstiller resultatene. Western blotting må brukes med nøyaktig implementering og forståelse for gjennomføringen for å oppnå riktige og gode analyser av resultatene [@bass2017]
