# Studiedesign

## Spørsmål

Det generelle spørsmålet de ulike studiene ser etter er effekten av blokkperiodisering på prestasjonsvariabler hos utholdenhetsutøvere. Det er vanskelig å sammenligne forskjellig treningsmetoder hos forskjellige typer utholdenhetsutøvere. Intervensjon over lengre tid gjør studiene mer kompliserte med tanke på individuell treningsrespons, mens kortere studier gir mulig for lite grunnlag til å kunne benytte seg av funnene for den enkelte utøver som skal trene over flere år for å nå et toppnivå.

Clark [@clark2014] ville se om ulike former for høyintensitettrening over en 7 dager "overload"- periode hos konkurransedyktige syklister, ville gi bedre prestasjonsfremmende effekt enn tradisjonell trening.

@ronnestad2016 ville undersøke om blokkperiodisering ville gi bedre prestasjonsfremmende effekt enn tradisjonell fordeling av høyintensitet- og lavintensitet trening hos langrennsutøvere på nasjonalt nivå.

McGawley [@mcgawley2017] ønsket å finne ut om blokkperiodisering-metoden ville forbedre prestasjonsvariabler hos langrennsutøvere, og samtidig finne ut om en slik intens treningsmetode kunne fremkalle symptomer på overbelastning og endret stemningsleie, som på sikt kunne føre til overtreningssyndrom.

Alle tre studiene tar for seg blokkperiodisering av høyintensitetstrening over en kortere tidsperiode. @mcgawley2017 ønsket i tillegg å finne ut om blokkperiodisering påvirker deltakerne på en uheldig måte som på sikt kan føre til overtreningssydrom, noe som vil være viktig for trenere og utøvere å kunne noe om, siden gjennomføring av blokkperiodisering er veldig ensidig og monoton trening.

## Alternativer

@clark2014 fremstiller spørsmålet som et spørsmål, der de forklarer at målet er å finne ut hvilken effekt de to ulike høyintensive programmene ville gi på fysiologiske- og prestasjonsvariabler hos konkurransedyktige syklister, ettersom de programmene simulerte den intensiteten de ville se i konkurranser. De ville også undersøke hvor lang tid restitusjon de ulike progammene krevde før adaptasjonene til treningen kom. Dette ble målt opp mot et tradisjonelt treningsprogram.

Spørsmålet til @ronnestad2016 er fremstilt som en hypotese, hvor de mener at blokkperiodisering (BT) vil gi overlegen forbedring på målinger tilknyttet aerob effekt i forhold til tradisjonell trening (TRAD).

@mcgawley2017 hadde en hypotese om at BLOCK ville få en høyere relativ økning i $\dot VO_{2max}$ og bedre prestasjon på 600m tempo, enn det EVEN ville, selv om BLOCK får mindre distanse og lavere hjertefrekvens under øktene. I tillegg forventet de høyere opplevd anstrengelse og dårligere opplevd restitusjon i BLOCK-gruppen.

@ronnestad2016 og @mcgawley2017 Valgte begge å forme spørsmålet om til en hypotese, mens @clark2014 å ha et spørsmål. Jeg synes dette passer bra da @ronnestad2016 og @mcgawley2017 kun fokuserte på én eksperimentel gruppe mot en kontrollgruppe, mens @clark2014 hadde to eksperimentelle grupper opp mot en kontrollgruppe. Hvis en studie har to eksperimentelle grupper så kan det bli vanskeligere å omforme spørsmålet til en hypotese.

## Logikk

@clark2014 : For å forberede seg til konkurranse periodiserer gjerne utholdenhetsutøvere treningen sin gjennom året. Mens lavintensiv trening for det meste forbedrer utholdenheten til utøverne, så er det den høyintensive treningen skal som har mest å si for å bygge utøvernes kondisjon og form. Selv om forskjellige lengder og former for høyintensiv trening har vist seg å være en effektiv treningsform, så har de siste undersøkelsene vært mer rettet mot organiseringen av de høyintensive øktene. Tidligere praksis har observert at høyintensive blokker, der utøverne konsentrerer de høyintensive øktene i en kortere periode eller deltar på konkurranser som oppkjøring, har vist seg å forbedre konkurranseformen inn mot viktige konkurranser. Noen studier peker på at korte blokker høyintensiv trening etterfulgt av roligere uker med trening øker prestasjonen til utøverne, som følge av en superkompensasjon. Denne metoden er blant annet kjent for å bli brukt under treningsleirer. Gjennom tidligere studier ser det ut til at syv dager med høyintensiv trening, er den beste lengden for å få prestasjonsutvikling uten at det gir for mye restitusjonstid før kompensasjonen kommer. Dermed ønsket forfatterne i denne studien å undersøke to forskjellige syvdagers blokker, hvor det ene programmet fokuserte på korte sprinter, mens det andre fokuserte på lengre sprinter. De to eksperimentelle gruppene ble målt opp mot en kontrollgruppe som bare trente tradisjonell trening.

@ronnestad2016 Langrennsutøvere baserer seg mest på polarisert trening, hvor mesteparten av øktene er HIT eller LIT økter. Tidligere studier viser ikke noe forbedring i prestasjonsvariabler som $\dot VO_{2max}$ gjennom treningsåret, og at det kan skyldes jevnlig bruk av HIT og LIT gjennom hele treningsåret. Det har blitt anslått at hvis hvis utøvere når et viss nivå, så skjer det ikke noe videre forbedring i $\dot VO_{2max}$. Det er blitt funnet ut at en annen fordeling i HIT og LIT uten å ofre noe av mengden av treningen kan gi forbedret prestasjon, testet hos syklister. Dette kaller de blokkperiodisering, som baserer seg på spesifikke konsentrerte treningsstimuli og vedlikehold av andre treningstimuli gjennom en kort periode på 1-4 uker. I og med at det pleier å være ganske jevn fordeling av HIT og LIT hver uke for langrennsløpere, så ønsket forfatterne å teste hvordan langrennsløpere responderer på blokkperiodisering. Forfatterne fant ut at syklister responderer bedre med blokkperiodisering enn med tradisjonell trening, noe som også kan være tilfelle med langrennsløpere. De valgte å gjennomføre prosjektet før konkurransesesongen startet, da annen forskning ikke fant noe signifikante forskjeller ved å utføre prosjektet i faser av treningsperioden hvor langrennsutøverne allerede kunne være i konkurranseform.

#### @mcgawley2017
Blokkperiodisering tar utgangspunkt i "overload" prinsippet. Hvor man skal få mye mengder av en bestemt type treningsøkt på kortere tid. I dette tilfellet undersøker de effekten av ni "HIT"økter som konsentreres i midten av en tre ukers periode, mot ni "HIT"økter jevnt fordelt på på de tre ukene. Tidligere undersøkelser støtter hypotesen om at blokkperiodisering kan øke prestasjonsvariabler i langrenn og sykkel, mens andre viser symptomer på fysisk overbelastning og endret stemningsleie. Med disse tidligere funnene ønsket de å undersøke mer om hvordan "HIT" økter, konsentrert på kort tid ville påvirke deltakerne både på prestasjonsvariabler, og på belastning fysisk og psykisk.

## Metoder

Studien til @clark2014 brukte i likhet med @ronnestad2016 randomisering basert på matchende resultater i $\dot VO_{2max}$, samt maks watt oppnådd under testen. Deltakerne bestod av 30 mannlige konkurransedyktige syklister, hvor 28 av dem fullførte studien. De hadde minimum to års erfaring fra konkurranser og ble klassifisert som erfaringgrad A eller B gjennom "Oceania amateur grading". Utvalget beskriver populasjonen i og med at det er konkurransedyktige syklister. Selv om de er på et amatørnivå, så er de utholdenhetsutøvere, noe som gjør at variablene til deltakerne ikke vil variere så mye.

@clark2014 kjørte to eksperimentelle grupper og en kontrollgruppe. De eksperimentelle gruppene hadde 4 forskjellige testtidspunkter underveis i prosjektet. Det var 7-10 dager mellom første og andre test, 14 dager mellom andre og tredje test, og 7 dager mellom tredje og fjerde (siste) test. Det var mellom test 2 og 3 den høyintensive 7-dagers blokken skulle gjennomføres, etterfulgt av 7 restitusjonsdager før test 3 startet. Kontrollgruppen gjennomførte bare tradisjonell trening med en mengde på minst 10 timer i uka. De skulle bare gjennomføre test 2 og 4. Testen bestod av en trinnvis økende belastningstest til utmattelse, og en 20 km simulert TT (time trial). I den trinnvise testen startet deltakerne å sykle på 100 watt. For hvert fjerde minutt økte belastningen med 40 watt, og en laktatmåling ble gjort de siste 30 sekundene før hvert trinn var ferdig, for å finne laktatterskel. De fortsatte å sykle til utmattelse, for å finne $\dot VO_{2max}$ eller $\dot VO_{2peak}$. Tempotesten var en simulert 20km test gjennom en PC som simulerte en fast løype med motbakker, nedoverbakker og flater. Dette var en ren prestasjonstest hvor det ble målt hvor lang tid de brukte på løypa og gjennomsnittwatt.

Variablene som blir brukt i studien er $\dot VO_{2peak}$, makswatt, laktatterskel, gjennomsnittwatt, arbeidsøkonomi og kadens. $\dot VO_{2peak}$ er maksimalt oksygenopptak oppnådd under testen, når oksygenopptaket ikke flater ut mot slutten. Om oksygenopptaket hadde flatet ut, ville variablene tilsvart $\dot VO_{2max}$. Makswatt er høyeste wattmåling oppnådd under en test eller en økt. Laktatterskel er et område hvor laktatnivået starter å øke mer i forhold til det kroppen klarer å kvitte seg med, og blir under studier standardisert som en terskellinje på 4mmol. Gjennomsnittwatt blir målt som snittverdien til effekten en utøver klarer å skape i en test eller en økt. Arbeidsøkonomi er hvor mye energi en utøver bruker på en viss hastighet eller gjennomsnittwatt. Kadens regnes som antall omdreinger i minuttet i sykkeltråkket. Det ble nevnt at deltakerne ble bedt om å holde rundt 90rpm under testene, som da vil si 90 omdreininger i minuttet eller "revolutions per minute". Variablene som kan relateres til spørsmålet er $\dot VO_{2peak}$, makswatt, laktatterskel, gjennomsnittwatt og arbeidsøkonomi da alle disse variablene kan påvirke prestasjonen til en utøver.

I de eksperimentelle gruppene skulle de igjennom 7 økter på 7 dager, og øktene bestod av rundt 120 minutter med en arbeid:hvile ratio på 1:5, der arbeid tilsvarer sprintene og hvile tilsvarer 50 sekunder rolig sykling. Deltakerne fikk ha selvvalgt 15 minutters oppvarming og nedtrapping. Gruppen med korte sprinter gjennomførte 25 sett av korte sprinter der et sett består av 5, 10 og 20 sekunders sprinter. Gruppen med de lange sprintene gjennomførte 10 sett med 15, 30 og 45 sekunders sprinter. Total arbeidsperiode og hvileperiode i den korte sprint gruppen ble 14.6 minutter arbeid og 73 minutter hvile, mot 15 minutter arbeid og 75 minutter hvile i den lange sprint gruppen. Deltakerne i begge sprintgruppene ble bedt om å holde høyest intensitet som mulig under sprintene, og sykle 30-40% av maks wattmålingen de oppnådde under testen. I restitusjonsperioden på 7 dager før test 3 kunne deltakerne bare gjennomføre rolige treningsøkter på under 120 minutter.

Med tanke på at det er et lite utvalg med i studien ser det ikke ut til at de estimerer den statistiske styrken før studiet, da de vet at de ikke kan nå den styrken de trenger basert på utvalget. I de statististiske analysene ble det brukt SPSS til signifikanttesting, der alpha ble satt som 0.05 (5%). "One way ANOVA ble brukt til å teste om de avhengige variablene under pre-testen viste noe signifikant forskjell mellom gruppene. Etter det brukte de en "repeated measures ANOVA til å sammenligne forandringene mellom gruppene fra test 1 til test 4. For å finne ut hvor forskjellene kom brukte de "pair wise comparisons" via ANOVA som brukte pre og post avhengige målingene for hver variabel. 90% konfidensintervall av den gjennomsnittlige effekten ble estimert i et regneark som bruker "unequal-variances t-statistic" til å utføre sammenligninger mellom gruppene. Disse sammenligningene ble beregnet for "change scores" mellom gjennomsnittverdiene til begge pre-testene (test 1 og test 2), og begge post-testene (test 3 og test 4) i begge eksperimentelle gruppene, samt test 2 og test 4 for kontrollgruppen. De kartlegget deretter betydningen av forandringene gjennom standardiserte "effect size" (ES) mål på 0.2 (liten), 0.5 (moderat) og 0.8 (stor). Med tanke på at det er et lite utvalg med i studien ser det ikke ut til at de estimerer statistist styrke

I studien til @ronnestad2016 brukte de randomisering av to og to personer med matchende $\dot VO_{2max}$, og plasserte dem tilfeldig i hver sin gruppe (BP eller TRAD). Med et lite utvalg kan man oppnå mer statistisk styrke med å randomisere på denne måten, da det blir lettere å to grupper med lik fordeling av nøkkelvariabler, som i dette tilfellet er $\dot VO_{2max}$. 22 langrennsutøvere og skiskyttere deltok i studien, og 19 fullførte. I BP var det 7 menn og 3 kvinner, og i TRAD 7 menn og 2 kvinner. Skiskytterne ble jevnt fordelt mellom de to gruppene og trente normal trening for langrennsløpere under intervensjonen. Alle konkurrerte på nasjonalt nivå, så vil si de representerer populasjonen i og med at det er langrennsløpere på høyt nivå de vi teste hypotesen.

Ser ikke at det står noe om hva de gjorde for å rekruttere deltakere, og heller ikke om de gjorde noe estimering av hvor mange deltakere de trengte for å få nok statistisk styrke.

Studien bestod av to testdager (pre- og post-test), og en intervensjon mellom disse testdagene. Testdagene bestod av en trinnvis submaksimal test for å finne 4mmol laktatterskel, og etter det en trinnvis maksimal test til utmattelse for å finne $\dot VO_{2max}$. Begge testene ble gjennomført på en rulleskimølle med samme rulleski og staver, og alle deltakerne skulle gjennomføre testene i teknikken skøyting. I intervensjonen var det to grupper, der den ene gruppen skulle gjennom en blokkperiodisering av treningen (BT), mens den andre gruppen skulle trene det vi kaller tradisjonell trening (TRAD). I BT startet deltakerne med 5 intervaller (HIT) den første uken, etterfulgt av 1 HIT i uke 2, 3 HIT i uke 3, 1 HIT i uke 4, og 1 HIT i uke 5. I TRAD skulle alle ukene bortsett fra uke 3 bestå av 2 HIT, der uke 3 fikk 3 HIT. Dermed ble det like mange HIT i både BT og TRAD. Deltakerne ble bedt om å gjennomføre minst 50% av HIT øktene i teknikken skøyting, men de kunne velge fritt om å bruke rulleski eller langrennski. HIT øktene bestod av 6 x 5 min eller 5 x 6 min. Lavintensitetøktene (LIT) ble individuelt tilpasset og skulle foregå i minst 1 time i hjertefrekvens (HR) sone 1.

Variabler som vi kan knytte til hypotesen er 4mmol laktatterskel og $\dot VO_{2max}$, da en høyreforskyvning av laktatterskelen til en deltaker fra pre- til post-test vil indikere at deltakeren kan jobbe på høyere aerob belastning (effekt). En forhøyning av $\dot VO_{2max}$ vil gjøre deltakeren i stand til å ta opp og forbruke mer oksygen som dermed vil forbedre den aerobe effekten.

Alle verdier presentert i tekst, figurer og tabeller er gjennomsnitt og standardavvik. Det ble brukt "two-way ANOVA" med Bonferroni "post-hoc" tester for å regne ut forskjellene mellom og innen gruppenes post- vs pre-verdier i laktatprofiltesten. "Paired student t-tests" og "unpaired student t-tests" ble brukt til å regne ut gruppeforskjeller i pre- til post-intervensjon på variablene $\dot VO_{2max}$, "peak aerobic power output" $\dot W_{max}$ og watt ved 4mmol laktat. For å sammenligne den praktiske betydningen av prestasjonsforbedringene ble "effect size" regnet ut som "Cohen's d".

@mcgawley2017 brukte et krysningsstudie (cross-over design) i prosjektet sitt. Det vil si at utvalget vi plukker fra populasjonen først blir delt opp tilfeldig i to grupper hvor begge skal gjennomføre begge en eksperimentell intervensjon og en kontroll intervensjon. Begge gruppene starter med pre-test, så starter den ene gruppen med eksperimentell intervensjon og den andre med kontroll. Etter at første intervensjon for begge gruppene er ferdig skal gruppene gjennom samme test som på pre-test (mid-test). Deretter blir det en liten pause for at gruppene skal komme ned igjen på "base-line", før de starter på neste intervensjon som er den intervensjonen de ikke har hatt enda (eksperimentell eller kontroll). Etter den intervensjonen er det da post-test som er identisk som på pre- og mid-test.

20 veltrente junior langrennsutøvere ble rekruttert til denne studien gjennom to svenske toppidrett skiskoler. Deltakerne bestod av 10 menn og 10 kvinner med minst seks års konkurranseerfaring i langrenn, som konkurrerte på nasjonalt nivå. Gjennomsnittlig treningsvolum lå på rundt 500 - 750 timer per år. 6 menn og 7 kvinner fullførte hele studien. Det at utvalget er junior-utøvere på nasjonalt nivå i en utholdenhetsidrett gjør at utvalget representerer populasjonen godt, i og med at det er utholdenhetsutøverere som er avhengig av å forbedre kondisjonsvariabler som $\dot VO_{2max}$.

Finner ikke ut om forfatterne kalkulerte hvor mange deltakere de trengte for å få god nok statistisk styrke, men 20 deltakere i et krysningsstudie skal være mer enn nok, i og med at alle deltakerne gjennomfører både eksperimentell og kontroll.

På testdagene møtte deltakerne opp på labratoriet uthvilt hvor de først måtte svare på et RESTQ-Sport spørreskjema, og gjennomføre spyttprøver. Etter det skulle de starte på de fysiologiske testene som inneholdt en trinnvis submaksimal test for å finne laktatterskel, etterfulgt av en trinnvis test til utmattelse. ($\dot VO_{2max}$ test). Deretter var det en times pause før 600 meter TT (time trial). Dette var en ny test som ingen av deltakterne var kjent med så det var først en "bli kjent" test før den virkelige testen startet to timer senere. Muskelbiopsier ble tatt av låret vastus lateralis tre dager før testdagen i uthvilt tilstand.Under intervensjonenene BLOCK og EVEN ble både høyintensitet- og lavintensivitettrening, i tillegg til styrketrening matchet, slik at det ble like høyt volum mellom de to intervensjonene. HIT bestod av 5 x 4 min med 6 min aktiv pause, utført ute i samme motbakke hver gang. Om deltakerne fikk problemer med rulleskiene fikk de løpe med staver istedet. Målet for HIT-øktene var å komme så langt mulig opp bakken, og samtidig kunne ha distribuert jevnt på alle dragene. I BLOCK ble de 9 øktene gjennomført i uke 2 av de 3 ukene, med 2 økter på dag 1, 2 og 5, med minst 5 timer pause mellom øktene. 1 økt ble gjennomført på dag 3, 6 og 7. Det ble brukt pulsmåler for å kartlegge intensiteten basert på de 5 aerobe intensitetsonene, samt subjektiv følelse gjennom borg skala. 30 min etter øktene skulle deltakerne oppgi en øktskår fra 1-10 på hvor hard økta var. Etter oppvarmingen på alle HIT og LIT skulle deltakerne svare hvor slitne de følte seg fra en skala fra 1-10, hvor 1 er veldig dårlig restituert, og 10 er svært godt restituert. RESTQ-spørreskjema ble gjennomført hver uke på en standardisert dag og tidspunkt i uka.

Bruk av $\dot VO_{2max}$ test under pre- og post-testing pluss pulsmåler vil gjøre den første hypotesen målbar. Kombinasjonen av pulsmåling og subjektiv følelse (under og etter øktene), samt RESTQ-spørreskjema vil også kunne gjøre den andre hypotesen målbar.

Forfatterne brukte statistikkprogrammet SPSS, Version 22. Der kalkulerte de gjennomsnitt og standard avvik, "Paired t-test" for å sammenligne responsen av HIT vs LIT, og BLOCK vs EVEN. "Unpaired t-test" for å sammmenligne responsen mellom menn vs kvinner. "Two-way ANOVA" ble også brukt. Ved hjelp av "effect size" fikk de kartlagt hvor stor treningseffekten var i BLOCK vs EVEN.

## Resultat

@clark2014 viste signifikante endringer mellom gruppene over tid i variablene $\dot VO_{2peak}$, 4mmol laktat, TT tid og TT gjennomsnittwatt. Sammenligning parvis mellom kontroll og korte sprint, samt kontroll og lange sprint, viste signifikante forskjeller i 4mmol laktat, TT tid og TT gjennomsnittwatt. I tillegg viste de en moderat til stor ES. Men i de sammenligningene var det ikke signifikant i variabelen $\dot VO_{2peak}$. Det var ingen forskjell mellom korte sprint og lange sprint gruppene, og de viste en relativt liten ES. Begge de eksperimentelle gruppene viste stor forbedring i den siste post-testen (test 4) 14 dager etter intervensjonen, mens korte sprint gruppa viste ikke like bra framgang på test 3, som vil si at de hadde forsinket framgang i forhold til lange sprint gruppa.

Studien til @ronnestad2016 viste at det ikke var noe forskjell i de ulike variablene mellom BT og TRAD før intervensjonen startet. Fra pre- til post-test var det en forbedring i $\dot VO_{2max}$ og "peak O2 pulse" hos BT, mens det ikke var noe forbedring i TRAD. Det var ikke noe signifikante relative forskjeller mellom BT og TRAD. $\dot W_{max}$ økte fra pre- til post-test i BT, mens det var ingen forskjell i TRAD. Den relative forskjellen mellom BT og TRAD var signifikant. Gjennomsnittlig "effect size" i de relative forskjellene $\dot VO_{2max}$ og $\dot W_{max}$ viste en moderat effekt i BT vs TRAD. Hjertefrekvensen ble målt lavere hos BT i post-test i forhold til pre-test, mens det ikke ble målt noe forskjell i TRAD. Selv om det ikke var noe forskjell i arbeidsøkonomi og laktatkonsentrasjon i løpet av intervensjonen, så økte 4mmol laktatterskel signifikant i BP, mens det ikke var noe forskjell i TRAD. Den relative forskjellen i 4mmol laktatterskel var høyere i BP enn i TRAD, med en høy effect size.

@mcgawley2017 viste ingen signifikante resultater i prestasjonsvariabler mellom intervensjonene og fra pre- til post-test i verken BLOCK eller EVEN. Det ble derimot signifikant tid fra pre- til post-test på 600m TT, testosteronkonsentrasjon i hvile, testosteron:cortisol ratio, gjennomsnittlig muskelfiber område, maksimal enzym aktivitet HAD og PFK, og i protein innhold PGC-1alfa. Opplevd restitusjon (pREC) var signifikant forbedret i EVEN i forhold til BLOCK hos alle deltakere. RESTQ-Sport var signifikant lavere i BLOCK etter uke 2 enn i EVEN, men ikke gjennom alle 3 ukene. Kvinnene hadde signifikant lavere restitusjonsstress tilstand enn herrene etter uke 2 i BLOCK.

## Begrunnelse

@clark2014 konkluderte med at 7-dagers blokkperiodisering har en betydelig effekt på prestasjon på 20 km TT. Det som er interessant å se er at korte sprint gruppa brukte lengre tid på hente seg inn enn lange sprint gruppa før framgangen kom. En potensiell forklaring som de nevner på det er at selv om korte sprint og lange sprint gruppa hadde lik total treningsvolum og sprintvolum, så ser det ut til at korte sprint gruppa jobbet mer intensivt under sprintene enn lange sprint gruppa. Det resulterer da til mer sliten muskulatur som trenger lenger tid til å hente seg før forbedringen kommer. Den praktiske "take home message" fra denne studien er at man heller bør ha en 7-dagers blokk med lange sprintdrag enn korte sprintdrag før et viktig mesterskap, da den lange sprint gruppa opplevde en kortere restitusjonstid. Samtidig vil de fraråde utøvere i vektbærende idretter å gjennomføre slik blokkperiodisering på grunn av økt sjanse for belastningsskader, inntil andre studier får undersøkt dette for vektbærende idretter nærmere.

I denne studien konkluderte @ronnestad2016 at blokkperiodisering av utholdenhetstrening har overlegent bedre effekt på flere av utholdenhets- og prestasjonsvariablene. Det er observert at en relativ forbedring i $\dot W_{max}$ kan være skillet på om man når en stor sportslig prestasjon eller ikke, og økningen i $\dot W_{max}$ virker som har spilt en rolle i økningen av prestasjon i BP. En relativ forbedring i 4mmol laktatterskel kan komme som en konsekvens av en forbedret $\dot VO_{2max}$ i løpet av intervensjonen. De begrunner at blokkperiodisering øker prestasjonen med at utøvere vanligvis har jevnlig distribusjon av HIT og LIT, og at en mer konsentrert HIT-uke etterfulgt av 1 økt HIT i vedlikeholdsukene gir bedre stimuli til å forbedre prestasjonsvariablene.

Basert på funnene til @mcgawley2017 var det ikke noe signifikant forskjell mellom BLOCK og EVEN, men heller signifikante funn uavhengig av intervensjon, så vil ikke denne studien støtte funn som viser at blokkperiodisering er en mye bedre treningsmetode for prestasjonsutvikling enn jevnt fordelt treningsmetode.Mulige grunner til dette er at denne studien ble gjennomført etter at skisesongen var ferdig, og ulempen med det er at langrennsutøvere kjører oftere HIT-økter mot slutten av sesongen enn i starten av sesongen. Forfatterne til denne studien mente at det kunne redusere effektiviteten av HIT-øktene i BLOCK, og at det kan være årsaken til at de ikke fant noe signifikant forskjell mellom BLOCK og EVEN. Det at Rønnestad et al ( 2014a,b, 2016) fant en forskjell kan være på grunn av at de gjennomførte studien før sesongen startet da langrennsløpere fokuserer mer på LIT i den perioden. En annen årsak forfatterne nevner er at de selv hadde satt alle HIT-øktene i uke 2 av BLOCK og ingen HIT i uke 3, der Rønnestad et al. (2014a,b, 2016) hadde minst 1 HIT som vedlikeholdsøkt hver uke utenom 5 HIT uka. Denne årsaken kan stemme med at det ble rapportert følelse av slapphet under uke 3 i BLOCK, som kun inneholdt LIT, noe som ikke var tilfelle i EVEN.

Som vi ser i studiene til @ronnestad2016 og @mcgawley2017, virker det som at at vedlitikeholdsøkter av HIT vil bidra til å holde litt på stimuliet, slik at det opparbeidede stimuliet ikke faller i de ukene etter den konsentrerte uka med HIT. Når det gjelder metoden til @clark2014, så vil flere grupper føre til færre forsøkspersoner per gruppe, som vil gjøre det vanskeligere å få nok statistisk styrke. Det blir i tillegg mye større jobb og mer avansert å regne statistikk mellom tre grupper kontra to. En metode for å øke statistisk styrke er å bruke et "cross-over design", hvor hver av deltakerne blir sin egen kontroll. Ulempen med slike design er at gjennomføringen av studiet ofte blir lengre og mer ressurskrevende. @clark2014 og @ronnestad2016 brukte begge randomisering av matchende deltakere i prestasjonsvariabler når de skulle fordele deltakerne til de forskjellige gruppene. Fordelen med å gjøre dette kommer i studier med så små utvalg som disse tre studiene har, er at det vil redusere risikoen for "confounding variables", som sikrer en bedre "base line" mellom gruppene. Ulempen er at det gjør rekrutteringen og randomiseringen mer komplisert, da enkelte deltakere må vente på en "match" før de blir randomisert til en gruppe. Alle tre studiene brukte forskjellige intervallprotokoller og ulik blokkprogram generelt, noe som vil gjøre det vanskelig å sammenligne og peke på enkeltfaktorer som årsaker til det ene eller andre resultatet.

