# Studie design

## Spørsmål

Det generelle spørsmålet de ulike studiene ser etter er effekten av blokkperiodisering på prestasjonsvariabler hos utholdenhetsutøvere. Det er vanskelig å sammenligne forskjellig treningsmetoder hos forskjellige typer utholdenhetsutøvere. Intervensjon over lengre tid gjør studiene mer kompliserte med tanke på individuell treningsrespons, mens kortere studier gir mulig for lite grunnlag til å kunne benytte seg av funnene for den enkelte utøver som skal trene over flere år for å nå et toppnivå.

@clark2014 ville se om ulike former for høyintensitettrening over en 7 dager "overload"- periode hos konkurransedyktige syklister, ville gi bedre prestasjonsfremmende effekt enn tradisjonell trening.

@ronnestad2016 ville undersøke om blokkperiodisering ville gi bedre prestasjonsfremmende effekt enn tradisjonell fordeling av høyintensitet- og lavintensitet trening hos langrennsutøvere på nasjonalt nivå.

@mcgawley2017 ønsket å finne ut om blokkperiodisering-metoden ville forbedre prestasjonsvariabler hos langrennsutøvere, og samtidig finne ut om en slik intens treningsmetode kunne fremkalle symptomer på overbelastning og endret stemningsleie, som på sikt kunne føre til overtreningssyndrom.

Alle tre studiene tar for seg blokkperiodisering av høyintensitetstrening over en kortere tidsperiode. @mcgawley2017 ønsket i tillegg å finne ut om blokkperiodisering påvirker deltakerne på en uheldig måte som på sikt kan føre til overtreningssydrom, noe som vil være viktig for trenere og utøvere å kunne noe om, siden gjennomføring av blokkperiodisering er veldig ensidig og monoton trening.

## Alternativer

@clark2014 fremstiller spørsmålet som et spørsmål, der de forklarer at målet er å finne ut hvilken effekt de to ulike høyintensive programmene ville gi på fysiologiske- og prestasjonsvariabler hos konkurransedyktige syklister, ettersom de programmene simulerte den intensiteten de ville se i konkurranser. De ville også undersøke hvor lang tid restitusjon de ulike progammene krevde før adaptasjonene til treningen kom. Dette ble målt opp mot et tradisjonelt treningsprogram.

Spørsmålet til @ronnestad2016 er fremstilt som en hypotese, hvor de mener at blokkperiodisering (BT) vil gi overlegen forbedring på målinger tilknyttet aerob effekt i forhold til tradisjonell trening (TRAD).

@mcgawley2017 hadde en hypotese om at BLOCK ville få en høyere relativ økning i $\dot VO_{2max}$ og bedre prestasjon på 600m tempo, enn det EVEN ville, selv om BLOCK får mindre distanse og lavere hjertefrekvens under øktene. I tillegg forventet de høyere opplevd anstrengelse og dårligere opplevd restitusjon i BLOCK-gruppen.

@ronnestad2016 og @mcgawley2017 Valgte begge å forme spørsmålet om til en hypotese, mens @clark2014 å ha et spørsmål. Jeg synes dette passer bra da @ronnestad2016 og @mcgawley2017 kun fokuserte på én eksperimentel gruppe mot en kontrollgruppe, mens @clark2014 hadde to eksperimentelle grupper opp mot en kontrollgruppe. Hvis en studie har to eksperimentelle grupper så kan det bli vanskeligere å omforme spørsmålet til en hypotese.

## Logikk

@clark2014 : For å forberede seg til konkurranse periodiserer gjerne utholdenhetsutøvere treningen sin gjennom året. Mens lavintensiv trening for det meste forbedrer utholdenheten til utøverne, så er det den høyintensive treningen skal som har mest å si for å bygge utøvernes kondisjon og form. Selv om forskjellige lengder og former for høyintensiv trening har vist seg å være en effektiv treningsform, så har de siste undersøkelsene vært mer rettet mot organiseringen av de høyintensive øktene. Tidligere praksis har observert at høyintensive blokker, der utøverne konsentrerer de høyintensive øktene i en kortere periode eller deltar på konkurranser som oppkjøring, har vist seg å forbedre konkurranseformen inn mot viktige konkurranser. Noen studier peker på at korte blokker høyintensiv trening etterfulgt av roligere uker med trening øker prestasjonen til utøverne, som følge av en superkompensasjon. Denne metoden er blant annet kjent for å bli brukt under treningsleirer. Gjennom tidligere studier ser det ut til at syv dager med høyintensiv trening, er den beste lengden for å få prestasjonsutvikling uten at det gir for mye restitusjonstid før kompensasjonen kommer. Dermed ønsket forfatterne i denne studien å undersøke to forskjellige syvdagers blokker, hvor det ene programmet fokuserte på korte sprinter, mens det andre fokuserte på lengre sprinter. De to eksperimentelle gruppene ble målt opp mot en kontrollgruppe som bare trente tradisjonell trening.

@ronnestad2016 : Langrennsutøvere baserer seg mest på polarisert trening, hvor mesteparten av øktene er HIT eller LIT økter. Tidligere studier viser ikke noe forbedring i prestasjonsvariabler som $\dot VO_{2max}$ gjennom treningsåret, og at det kan skyldes jevnlig bruk av HIT og LIT gjennom hele treningsåret. Det har blitt anslått at hvis hvis utøvere når et viss nivå, så skjer det ikke noe videre forbedring i $\dot VO_{2max}$. Det er blitt funnet ut at en annen fordeling i HIT og LIT uten å ofre noe av mengden av treningen kan gi forbedret prestasjon, testet hos syklister. Dette kaller de blokkperiodisering, som baserer seg på spesifikke konsentrerte treningsstimuli og vedlikehold av andre treningstimuli gjennom en kort periode på 1-4 uker. I og med at det pleier å være ganske jevn fordeling av HIT og LIT hver uke for langrennsløpere, så ønsket forfatterne å teste hvordan langrennsløpere responderer på blokkperiodisering. Forfatterne fant ut at syklister responderer bedre med blokkperiodisering enn med tradisjonell trening, noe som også kan være tilfelle med langrennsløpere. De valgte å gjennomføre prosjektet før konkurransesesongen startet, da annen forskning ikke fant noe signifikante forskjeller ved å utføre prosjektet i faser av treningsperioden hvor langrennsutøverne allerede kunne være i konkurranseform.

@ronnestad2016 : Langrennsutøvere baserer seg mest på polarisert trening, hvor mesteparten av øktene er HIT eller LIT økter. Tidligere studier viser ikke noe forbedring i prestasjonsvariabler som $\dot VO_{2max}$ gjennom treningsåret, og at det kan skyldes jevnlig bruk av HIT og LIT gjennom hele treningsåret. Det har blitt anslått at hvis hvis utøvere når et viss nivå, så skjer det ikke noe videre forbedring i $\dot VO_{2max}$. Det er blitt funnet ut at en annen fordeling i HIT og LIT uten å ofre noe av mengden av treningen kan gi forbedret prestasjon, testet hos syklister. Dette kaller de blokkperiodisering, som baserer seg på spesifikke konsentrerte treningsstimuli og vedlikehold av andre treningstimuli gjennom en kort periode på 1-4 uker. I og med at det pleier å være ganske jevn fordeling av HIT og LIT hver uke for langrennsløpere, så ønsket forfatterne å teste hvordan langrennsløpere responderer på blokkperiodisering. Forfatterne fant ut at syklister responderer bedre med blokkperiodisering enn med tradisjonell trening, noe som også kan være tilfelle med langrennsløpere. De valgte å gjennomføre prosjektet før konkurransesesongen startet, da annen forskning ikke fant noe signifikante forskjeller ved å utføre prosjektet i faser av treningsperioden hvor langrennsutøverne allerede kunne være i konkurranseform.
